#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 3.22-{branch}-{build}

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  sonarcloudtoken:
    secure: VMTLc0vSBXvIH5sBuyKY6ri8IL3I5kYpXnCK3xYPkfXK0+tFnIwlotzE3Gn5Yu4u

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  parallel: true
  project: XOutput.sln
  include_nuget_references: true
  # MSBuild verbosity level - quiet|minimal|normal|detailed
  verbosity: normal
  
build_script:
 - choco install "sonarscanner-msbuild-net46" -y
 - SonarScanner.MSBuild.exe begin /k:"XOutput" /d:"sonar.host.url=https://sonarcloud.io" /o:"csutorasa" /d:"sonar.login=%sonarcloudtoken%"
 - msbuild /verbosity:quiet "XOutput.sln"
 - SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloudtoken%"
  
before_build:
  - nuget restore
  
after_build:
  - 7z a XOutput.zip %APPVEYOR_BUILD_FOLDER%\XOutput\bin\Release\XOutput.exe

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: XOutput.zip
    name: XOutput

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:

on_failure:

on_finish:


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to:
      - csutorasa@gmail.com
    on_build_success: false
